name: Daily Activity

on:
  schedule:
    - cron: "30 18 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  daily-activity:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update activity log
        run: |
          echo "Daily activity - $(TZ=Asia/Kolkata date +'%Y-%m-%d')" >> activity.log

      - name: Commit changes
        run: |
          git config user.name "Raghavratan2003"
          git config user.email "rghvrtnydv2003@gmail.com"

          git add activity.log

          CURRENT_DATE=$(TZ=Asia/Kolkata date '+%Y-%m-%dT%H:%M:%S%z')

          GIT_AUTHOR_DATE="$CURRENT_DATE" \
          GIT_COMMITTER_DATE="$CURRENT_DATE" \
          git commit -m "Daily activity update"

          git push
